services:
  database:
    image: bitnami/postgresql:latest
    container_name: dailydiet-database
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dailydiet
    ports:
      - "5432:5432"
